import { Toaster } from 'sonner'
import './globals.css'
import ModalProvider from '../providers/modal-provider'


export const metadata = {
  title: 'Cliniconnect',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ModalProvider/>
        {children}
        <Toaster position='top-center' richColors/>
      </body>
    </html>
  )
}
