import { Toaster } from 'sonner'
import { AuthProvider } from '@/providers/auth-provider'
import './globals.css'

export const metadata = {
  title: 'Cliniconnect',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
          <Toaster position='top-center' richColors/>
        </AuthProvider>
      </body>
    </html>
  )
}
