import { Toaster } from 'sonner'
import './globals.css'


export const metadata = {
  title: 'Cliniconnect',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          {children}
          <Toaster position='top-center' richColors/>
      </body>
    </html>
  )
}
